// ─── Theme Presets ───────────────────────────────────────────────────────────
// Each theme follows the same color-key contract so components can swap themes
// without changing logic. `spacing`, `radius`, `typography` and `shadow` are
// theme-independent and live in theme.js.

export const themePresets = {
  // ── Default (Violet) ────────────────────────────────────────────────────────
  default: {
    id: 'default',
    name: 'Violet',
    emoji: '💜',
    colors: {
      primary: '#7c3aed',
      primaryLight: '#ede9fe',
      primaryDark: '#5b21b6',
      gradientStart: '#7c3aed',
      gradientEnd: '#5b21b6',
      background: '#f8f5ff',
      card: '#ffffff',
      border: '#e5e7eb',
      textPrimary: '#1e1b4b',
      textSecondary: '#6b7280',
      textMuted: '#9ca3af',
      income: '#22c55e',
      incomeLight: '#dcfce7',
      expense: '#ef4444',
      expenseLight: '#fee2e2',
      warning: '#f59e0b',
      warningLight: '#fef3c7',
      danger: '#ef4444',
      dangerLight: '#fee2e2',
      success: '#22c55e',
      successLight: '#dcfce7',
      info: '#3b82f6',
      infoLight: '#dbeafe',
      goal: '#8b5cf6',
      goalLight: '#ede9fe',
      white: '#ffffff',
      black: '#000000',
    },
  },

  // ── AMOLED ──────────────────────────────────────────────────────────────────
  amoled: {
    id: 'amoled',
    name: 'AMOLED',
    emoji: '🌑',
    colors: {
      primary: '#a78bfa',
      primaryLight: '#1e1b2e',
      primaryDark: '#7c3aed',
      gradientStart: '#1a1a2e',
      gradientEnd: '#16213e',
      background: '#000000',
      card: '#0d0d0d',
      border: '#1f1f1f',
      textPrimary: '#f1f1f1',
      textSecondary: '#a0a0a0',
      textMuted: '#606060',
      income: '#4ade80',
      incomeLight: '#052e16',
      expense: '#f87171',
      expenseLight: '#2d0000',
      warning: '#fbbf24',
      warningLight: '#1c1300',
      danger: '#f87171',
      dangerLight: '#2d0000',
      success: '#4ade80',
      successLight: '#052e16',
      info: '#60a5fa',
      infoLight: '#0d1f3c',
      goal: '#c084fc',
      goalLight: '#1c0d2e',
      white: '#f1f1f1',
      black: '#000000',
    },
  },

  // ── Pastel ──────────────────────────────────────────────────────────────────
  pastel: {
    id: 'pastel',
    name: 'Pastel',
    emoji: '🌸',
    colors: {
      primary: '#c084fc',
      primaryLight: '#fae8ff',
      primaryDark: '#a855f7',
      gradientStart: '#e9d5ff',
      gradientEnd: '#c084fc',
      background: '#fdf4ff',
      card: '#ffffff',
      border: '#f3e8ff',
      textPrimary: '#3b0764',
      textSecondary: '#7e22ce',
      textMuted: '#a78bfa',
      income: '#86efac',
      incomeLight: '#f0fdf4',
      expense: '#fda4af',
      expenseLight: '#fff1f2',
      warning: '#fde68a',
      warningLight: '#fffbeb',
      danger: '#fda4af',
      dangerLight: '#fff1f2',
      success: '#86efac',
      successLight: '#f0fdf4',
      info: '#93c5fd',
      infoLight: '#eff6ff',
      goal: '#c084fc',
      goalLight: '#fae8ff',
      white: '#ffffff',
      black: '#1a1a2e',
    },
  },

  // ── Cyberpunk ────────────────────────────────────────────────────────────────
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    emoji: '⚡',
    colors: {
      primary: '#00f5d4',
      primaryLight: '#001f1b',
      primaryDark: '#00b4a0',
      gradientStart: '#0f0f1a',
      gradientEnd: '#1a0033',
      background: '#0a0a0f',
      card: '#12121f',
      border: '#1e1e3a',
      textPrimary: '#e0e0ff',
      textSecondary: '#8888bb',
      textMuted: '#444466',
      income: '#00f5d4',
      incomeLight: '#001f1b',
      expense: '#ff0090',
      expenseLight: '#1f0012',
      warning: '#f5c400',
      warningLight: '#1f1800',
      danger: '#ff0090',
      dangerLight: '#1f0012',
      success: '#00f5d4',
      successLight: '#001f1b',
      info: '#7b2fff',
      infoLight: '#100025',
      goal: '#ff0090',
      goalLight: '#1f0012',
      white: '#e0e0ff',
      black: '#0a0a0f',
    },
  },

  // ── Minimal ──────────────────────────────────────────────────────────────────
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    emoji: '⬜',
    colors: {
      primary: '#111827',
      primaryLight: '#f3f4f6',
      primaryDark: '#030712',
      gradientStart: '#374151',
      gradientEnd: '#111827',
      background: '#f9fafb',
      card: '#ffffff',
      border: '#e5e7eb',
      textPrimary: '#111827',
      textSecondary: '#6b7280',
      textMuted: '#9ca3af',
      income: '#059669',
      incomeLight: '#ecfdf5',
      expense: '#dc2626',
      expenseLight: '#fef2f2',
      warning: '#d97706',
      warningLight: '#fffbeb',
      danger: '#dc2626',
      dangerLight: '#fef2f2',
      success: '#059669',
      successLight: '#ecfdf5',
      info: '#2563eb',
      infoLight: '#eff6ff',
      goal: '#7c3aed',
      goalLight: '#f5f3ff',
      white: '#ffffff',
      black: '#000000',
    },
  },

  // ── Sakura ───────────────────────────────────────────────────────────────────
  sakura: {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌺',
    colors: {
      primary: '#e11d74',
      primaryLight: '#fce7f3',
      primaryDark: '#9d174d',
      gradientStart: '#f9a8d4',
      gradientEnd: '#e11d74',
      background: '#fff0f6',
      card: '#ffffff',
      border: '#fce7f3',
      textPrimary: '#500724',
      textSecondary: '#9d174d',
      textMuted: '#f472b6',
      income: '#22c55e',
      incomeLight: '#dcfce7',
      expense: '#e11d74',
      expenseLight: '#fce7f3',
      warning: '#f59e0b',
      warningLight: '#fef3c7',
      danger: '#e11d74',
      dangerLight: '#fce7f3',
      success: '#22c55e',
      successLight: '#dcfce7',
      info: '#ec4899',
      infoLight: '#fdf2f8',
      goal: '#db2777',
      goalLight: '#fce7f3',
      white: '#ffffff',
      black: '#1a0010',
    },
  },

  // ── Finance Green ─────────────────────────────────────────────────────────────
  financeGreen: {
    id: 'financeGreen',
    name: 'Finance',
    emoji: '💹',
    colors: {
      primary: '#15803d',
      primaryLight: '#dcfce7',
      primaryDark: '#14532d',
      gradientStart: '#15803d',
      gradientEnd: '#14532d',
      background: '#f0fdf4',
      card: '#ffffff',
      border: '#bbf7d0',
      textPrimary: '#14532d',
      textSecondary: '#166534',
      textMuted: '#4ade80',
      income: '#16a34a',
      incomeLight: '#dcfce7',
      expense: '#dc2626',
      expenseLight: '#fee2e2',
      warning: '#ca8a04',
      warningLight: '#fef9c3',
      danger: '#dc2626',
      dangerLight: '#fee2e2',
      success: '#16a34a',
      successLight: '#dcfce7',
      info: '#0284c7',
      infoLight: '#e0f2fe',
      goal: '#15803d',
      goalLight: '#dcfce7',
      white: '#ffffff',
      black: '#000000',
    },
  },

  // ── Retro Terminal ───────────────────────────────────────────────────────────
  retroTerminal: {
    id: 'retroTerminal',
    name: 'Terminal',
    emoji: '🖥️',
    colors: {
      primary: '#00ff41',
      primaryLight: '#001a00',
      primaryDark: '#00cc33',
      gradientStart: '#000800',
      gradientEnd: '#001200',
      background: '#000800',
      card: '#000d00',
      border: '#003300',
      textPrimary: '#00ff41',
      textSecondary: '#00cc33',
      textMuted: '#008800',
      income: '#00ff41',
      incomeLight: '#001a00',
      expense: '#ff3300',
      expenseLight: '#1a0000',
      warning: '#ffaa00',
      warningLight: '#1a0e00',
      danger: '#ff3300',
      dangerLight: '#1a0000',
      success: '#00ff41',
      successLight: '#001a00',
      info: '#00aaff',
      infoLight: '#000d1a',
      goal: '#00ff41',
      goalLight: '#001a00',
      white: '#00ff41',
      black: '#000800',
    },
  },

  // ── Christmas ────────────────────────────────────────────────────────────────
  christmas: {
    id: 'christmas',
    name: 'Christmas',
    emoji: '🎄',
    seasonal: true,
    colors: {
      primary: '#c0392b',
      primaryLight: '#fce8e6',
      primaryDark: '#922b21',
      gradientStart: '#1a5c2a',
      gradientEnd: '#c0392b',
      background: '#fff8f8',
      card: '#ffffff',
      border: '#f8d7da',
      textPrimary: '#1c1c1c',
      textSecondary: '#5a3a3a',
      textMuted: '#a05050',
      income: '#1a8c35',
      incomeLight: '#d4edda',
      expense: '#c0392b',
      expenseLight: '#fce8e6',
      warning: '#e67e22',
      warningLight: '#fdebd0',
      danger: '#c0392b',
      dangerLight: '#fce8e6',
      success: '#1a8c35',
      successLight: '#d4edda',
      info: '#1a5c2a',
      infoLight: '#d4edda',
      goal: '#c0392b',
      goalLight: '#fce8e6',
      white: '#ffffff',
      black: '#1c1c1c',
    },
  },

  // ── Halloween ────────────────────────────────────────────────────────────────
  halloween: {
    id: 'halloween',
    name: 'Halloween',
    emoji: '🎃',
    seasonal: true,
    colors: {
      primary: '#e67e22',
      primaryLight: '#1a0a30',
      primaryDark: '#ca6f1e',
      gradientStart: '#0d0d1a',
      gradientEnd: '#1a0a30',
      background: '#0a0a14',
      card: '#12101e',
      border: '#2a1840',
      textPrimary: '#f0e0ff',
      textSecondary: '#b090d0',
      textMuted: '#705090',
      income: '#e67e22',
      incomeLight: '#2a1800',
      expense: '#8b1538',
      expenseLight: '#200008',
      warning: '#e67e22',
      warningLight: '#2a1800',
      danger: '#8b1538',
      dangerLight: '#200008',
      success: '#e67e22',
      successLight: '#2a1800',
      info: '#7c3aed',
      infoLight: '#1a0a30',
      goal: '#e67e22',
      goalLight: '#2a1800',
      white: '#f0e0ff',
      black: '#0a0a14',
    },
  },

  // ── Valentine ─────────────────────────────────────────────────────────────────
  valentine: {
    id: 'valentine',
    name: "Valentine's",
    emoji: '💕',
    seasonal: true,
    colors: {
      primary: '#e91e8c',
      primaryLight: '#fce4f0',
      primaryDark: '#c0176f',
      gradientStart: '#ff69b4',
      gradientEnd: '#e91e8c',
      background: '#fff0f7',
      card: '#ffffff',
      border: '#fad2e8',
      textPrimary: '#3d0026',
      textSecondary: '#8b004d',
      textMuted: '#e91e8c',
      income: '#22c55e',
      incomeLight: '#dcfce7',
      expense: '#e91e8c',
      expenseLight: '#fce4f0',
      warning: '#f59e0b',
      warningLight: '#fef3c7',
      danger: '#e91e8c',
      dangerLight: '#fce4f0',
      success: '#22c55e',
      successLight: '#dcfce7',
      info: '#e91e8c',
      infoLight: '#fce4f0',
      goal: '#e91e8c',
      goalLight: '#fce4f0',
      white: '#ffffff',
      black: '#3d0026',
    },
  },

  // ── Summer ────────────────────────────────────────────────────────────────────
  summer: {
    id: 'summer',
    name: 'Summer',
    emoji: '🌅',
    seasonal: true,
    colors: {
      primary: '#f97316',
      primaryLight: '#fff7ed',
      primaryDark: '#ea6c0a',
      gradientStart: '#f97316',
      gradientEnd: '#fbbf24',
      background: '#fffbf5',
      card: '#ffffff',
      border: '#fed7aa',
      textPrimary: '#431407',
      textSecondary: '#9a3412',
      textMuted: '#fb923c',
      income: '#16a34a',
      incomeLight: '#dcfce7',
      expense: '#f97316',
      expenseLight: '#fff7ed',
      warning: '#fbbf24',
      warningLight: '#fef9c3',
      danger: '#ef4444',
      dangerLight: '#fee2e2',
      success: '#16a34a',
      successLight: '#dcfce7',
      info: '#0ea5e9',
      infoLight: '#e0f2fe',
      goal: '#f97316',
      goalLight: '#fff7ed',
      white: '#ffffff',
      black: '#431407',
    },
  },

  // ── Rainy Season ──────────────────────────────────────────────────────────────
  rainy: {
    id: 'rainy',
    name: 'Rainy Day',
    emoji: '🌧️',
    seasonal: true,
    colors: {
      primary: '#0369a1',
      primaryLight: '#e0f2fe',
      primaryDark: '#075985',
      gradientStart: '#0c4a6e',
      gradientEnd: '#0369a1',
      background: '#f0f8ff',
      card: '#ffffff',
      border: '#bae6fd',
      textPrimary: '#0c2d48',
      textSecondary: '#1e5f8a',
      textMuted: '#60a5fa',
      income: '#059669',
      incomeLight: '#ecfdf5',
      expense: '#0369a1',
      expenseLight: '#e0f2fe',
      warning: '#d97706',
      warningLight: '#fffbeb',
      danger: '#dc2626',
      dangerLight: '#fef2f2',
      success: '#059669',
      successLight: '#ecfdf5',
      info: '#0369a1',
      infoLight: '#e0f2fe',
      goal: '#0369a1',
      goalLight: '#e0f2fe',
      white: '#ffffff',
      black: '#0c2d48',
    },
  },

  // ── New Year ──────────────────────────────────────────────────────────────────
  newYear: {
    id: 'newYear',
    name: 'New Year',
    emoji: '🎆',
    seasonal: true,
    colors: {
      primary: '#f59e0b',
      primaryLight: '#1a1600',
      primaryDark: '#b45309',
      gradientStart: '#0d0d0d',
      gradientEnd: '#1a1200',
      background: '#0a0a0a',
      card: '#141200',
      border: '#2a2000',
      textPrimary: '#fffbe6',
      textSecondary: '#d4a900',
      textMuted: '#7a5c00',
      income: '#f59e0b',
      incomeLight: '#1a1600',
      expense: '#ef4444',
      expenseLight: '#1a0000',
      warning: '#f59e0b',
      warningLight: '#1a1600',
      danger: '#ef4444',
      dangerLight: '#1a0000',
      success: '#f59e0b',
      successLight: '#1a1600',
      info: '#a78bfa',
      infoLight: '#100025',
      goal: '#f59e0b',
      goalLight: '#1a1600',
      white: '#fffbe6',
      black: '#0a0a0a',
    },
  },
};

export const THEME_ORDER = [
  'default',
  'minimal',
  'pastel',
  'sakura',
  'financeGreen',
  'amoled',
  'cyberpunk',
  'retroTerminal',
  'christmas',
  'halloween',
  'valentine',
  'summer',
  'rainy',
  'newYear',
];

/**
 * Detect the appropriate seasonal theme based on the current date.
 * Returns a theme ID or null if no seasonal theme applies.
 *
 * Philippine seasonal calendar:
 *   Jan 1–7       → New Year
 *   Feb 1–14      → Valentine's
 *   Mar 15–Jun 15 → Summer (Taginit)
 *   Jun 16–Oct 31 → Rainy (Ulan)
 *   Oct 1–31      → Halloween (overrides Rainy in October)
 *   Nov 25–Jan 7  → Christmas / Holiday season
 */
export function detectSeasonalTheme() {
  const now = new Date();
  const month = now.getMonth() + 1; // 1-12
  const day = now.getDate();

  // New Year window (Jan 1-7)
  if (month === 1 && day <= 7) return 'newYear';

  // Valentine's (Feb 1-14)
  if (month === 2 && day <= 14) return 'valentine';

  // Summer — Philippines hot season (Mar 15 - Jun 15)
  if (
    (month === 3 && day >= 15) ||
    month === 4 ||
    month === 5 ||
    (month === 6 && day <= 15)
  ) return 'summer';

  // Halloween (October — takes priority over rainy)
  if (month === 10) return 'halloween';

  // Rainy season (Jun 16 - Sep 30)
  if (
    (month === 6 && day >= 16) ||
    month === 7 ||
    month === 8 ||
    month === 9
  ) return 'rainy';

  // Christmas / Holiday (Nov 25 - Dec 31)
  if (month === 12 || (month === 11 && day >= 25)) return 'christmas';

  // No specific season
  return null;
}
